providers:                   # contains information about known providers
- id: managedk8s             # unique provider identifier
  name: "Managed Kubernetes" # user friendly name of the provider
  metadata:
    foo: bar
  args:
    kubeconfigPath: /tmp/kubeconfig.config  # path to cluster admin kubeconfig
  rulesets:
  - id: disa-kubernetes-stig
    name: DISA Kubernetes Security Technical Implementation Guide
    version: v1r11
    ruleOptions:
    # - ruleID: "242383"
    #   args:
    #     acceptedResources:
    #     - apiVersion: "v1"
    #       # if set to "*" match all kinds
    #       kind: "Pod"
    #       matchLabels:
    #         foo: bar
    #       # Defaults to ["default", "kube-public", "kube-node-lease"]
    #       namespaceNames:
    #       - default
    #       - kube-public
    #       - kube-node-lease
    #       justification: "justification"
    #       # relates to the result status in the report
    #       # can be set to Passed or Accepted. Defaults to Accepted
    #       status: Passed
    # - ruleID: "242393"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    # - ruleID: "242394"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    # - ruleID: "242396"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    # - ruleID: "242400"
    #   args:
    #     kubeProxyMatchLabels:
    #       foo: bar
    # - ruleID: "242404"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    # - ruleID: "242406"
    #   args:
    #     # Node labels used to group nodes by specified
    #     # label value combinations. Only one node per
    #     # combination will be tested
    #     nodeGroupByLabels:
    #     - foo
    #     expectedFileOwner:
    #       users: ["0"]
    #       groups: ["0"]
    # - ruleID: "242407"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    # - ruleID: "242414"
    #   args:
    #     acceptedPods:
    #     - podMatchLabels:
    #         label: foo
    #       namespaceMatchLabels:
    #         label: foo
    #       justification: "justification"
    #       ports:
    #       - 53
    # - ruleID: "242415"
    #   args:
    #     acceptedPods:
    #     - podMatchLabels:
    #         label: foo
    #       namespaceMatchLabels:
    #         label: foo
    #       justification: "justification"
    #       environmentVariables:
    #       - FOO_BAR
    # - ruleID: "242417"
    #   args:
    #     acceptedPods:
    #     - podMatchLabels:
    #         foo: bar
    #       namespaceNames:
    #       - kube-system
    #       - kube-public
    #       - kube-node-lease
    #       justification: "justification"
    #       # relates to the result status in the report
    #       # can be set to Passed or Accepted. Defaults to Accepted
    #       status: Passed
    # - ruleID: "242447"
    #   args:
    #     kubeProxyMatchLabels:
    #       foo: bar
    # - ruleID: "242448"
    #   args:
    #     kubeProxyMatchLabels:
    #       foo: bar
    #     expectedFileOwner:
    #       users: ["0"]
    #       groups: ["0"]
    # - ruleID: "242449"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    # - ruleID: "242450"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    #     expectedFileOwner:
    #       users: ["0"]
    #       groups: ["0"]
    # - ruleID: "242451"
    #   args:
    #     kubeProxyMatchLabels:
    #       foo: bar
    #     nodeGroupByLabels:
    #     - foo
    #     expectedFileOwner:
    #       users: ["0"]
    #       groups: ["0"]
    # - ruleID: "242452"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    # - ruleID: "242453"
    #   args:
    #     nodeGroupByLabels:
    #     - foo
    #     expectedFileOwner:
    #       users: ["0"]
    #       groups: ["0"]
    # - ruleID: "242466"
    #   args:
    #     kubeProxyMatchLabels:
    #       foo: bar
    #     nodeGroupByLabels:
    #     - foo
    # - ruleID: "242467"
    #   args:
    #     kubeProxyMatchLabels:
    #       foo: bar
    #     nodeGroupByLabels:
    #     - foo
output:
  path: /tmp/test-output.json  # optional, path to summary json report
  minStatus: Passed
