name: diki-updater

on:
  release:
    types:
      - published
jobs:
  update_diki_in_homebrew_tap_and_chocolatey_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
        with:
          go-version: '1.21.1'
      - name: Build the binary-files
        id: build_binary_files
        run: |
          sudo apt-get update
          sudo apt-get install make -y
          make build
          echo "latest_release_filtered_tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
