name: diki-uploader

on:
  release:
    types:
      - published
jobs:
  upload_diki_binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.23.5'
      - name: Build the binary-files
        id: build_binary_files
        run: |
          sudo apt-get update
          sudo apt-get install make -y
          make build
          echo "latest_release_filtered_tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Upload binaries to release
        uses: AButler/upload-release-assets@c94805dc72e4b20745f543da0f62eaee7722df7a # v2.0.2
        with:
          files: 'bin/diki-darwin-amd64;bin/diki-darwin-arm64;bin/diki-linux-amd64;bin/diki-linux-arm64;bin/diki-windows-amd64'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.latest_release_filtered_tag }}
      - name: Send update with latest versions to ${{ github.repository_owner }}/homebrew-tap
        if: github.event.release.prerelease == false
        run: |
          latest_release_filtered_tag=${{ env.latest_release_filtered_tag }}
          darwin_sha256sum_amd64=$(sha256sum bin/diki-darwin-amd64 | awk '{print $1}')
          darwin_sha256sum_arm64=$(sha256sum bin/diki-darwin-arm64 | awk '{print $1}')
          linux_sha256sum_amd64=$(sha256sum bin/diki-linux-amd64 | awk '{print $1}')
          linux_sha256sum_arm64=$(sha256sum bin/diki-linux-arm64 | awk '{print $1}')
          data='{"event_type": "update", "client_payload": { "component": "diki", "tag": "'"$latest_release_filtered_tag"'", "darwin_sha_amd64": "'"$darwin_sha256sum_amd64"'", "darwin_sha_arm64": "'"$darwin_sha256sum_arm64"'", "linux_sha_amd64": "'"$linux_sha256sum_amd64"'", "linux_sha_arm64": "'"$linux_sha256sum_arm64"'"}}'
          echo "${data}"
          curl -X POST https://api.github.com/repos/${{ github.repository_owner }}/homebrew-tap/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u "${{ secrets.ACCESS_TOKEN }}" \
          --data "${data}"
